### ISSUE TITLE
prod rebuilds fail

### ISSUE THREAD

**Issue by stefanpenner** [jonathanKingston/ember-cli-sri#15]
```
ile deleted adapters/4913
file changed adapters/pokemon.js
ENOENT: no such file or directory, stat '/Users/stefanpenner/tmp/pokedex/tmp/srihash_assets-output_path-pLI5BuHh.tmp/as
sets/pokedex.css'
Error: ENOENT: no such file or directory, stat '/Users/stefanpenner/tmp/pokedex/tmp/srihash_assets-output_path-pLI5BuHh
.tmp/assets/pokedex.css'
    at Error (native)
    at Object.fs.statSync (fs.js:892:18)
    at copyDereferenceSync (/Users/stefanpenner/tmp/pokedex/node_modules/ember-cli/node_modules/ember-cli-copy-derefere
nce/index.js:13:21)
    at copyDereferenceSync (/Users/stefanpenner/tmp/pokedex/node_modules/ember-cli/node_modules/ember-cli-copy-derefere
nce/index.js:31:7)
    at Function.copyDereferenceSync [as sync] (/Users/stefanpenner/tmp/pokedex/node_modules/ember-cli/node_modules/embe
r-cli-copy-dereference/index.js:31:7)
    at /Users/stefanpenner/tmp/pokedex/node_modules/ember-cli/lib/models/builder.js:144:19
    at lib$rsvp$$internal$$initializePromise (/Users/stefanpenner/tmp/pokedex/node_modules/ember-cli/node_modules/rsvp/
dist/rsvp.js:541:9)
    at PromiseExt.lib$rsvp$promise$$Promise (/Users/stefanpenner/tmp/pokedex/node_modules/ember-cli/node_modules/rsvp/d
ist/rsvp.js:757:9)
    at new PromiseExt (/Users/stefanpenner/tmp/pokedex/node_modules/ember-cli/lib/ext/promise.js:32:8)
    at Class.module.exports.Task.extend.copyToOutputPath (/Users/stefanpenner/tmp/pokedex/node_modules/ember-cli/lib/mo
dels/builder.js:139:12)
```

**Comment by jonathanKingston** [comment]
@stefanpenner is this still happening, surely not?
